=== sadman2762/WebTech/directory.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT directory (directory*, file*)>
<!ATTLIST directory name CDATA #REQUIRED>

<!ELEMENT file EMPTY>
<!ATTLIST file name CDATA #REQUIRED size CDATA #REQUIRED>

=== sadman2762/WebTech/directory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE directory SYSTEM "directory.dtd">
<?xml-stylesheet href="directory.css" type="text/css"?>
<directory name="project">
    <directory name="src">
        <directory name="main">
            <directory name="java">
                <file name="Main.java" size="2048"/>
                <file name="Util.java" size="1024"/>
             </directory>

        </directory>

        <directory name="test">

        </directory>
    </directory>
    <file name="LICENSE.txt" size="11358"/>
    <file name="pom.xml" size="1024"/>
    <file name="README.md" size="512"/>
</directory>
